In [17]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

%matplotlib inline
sns.set_theme(style="whitegrid")

In [3]:
#Reads the .csv file
df = pd.read_csv(r"C:\Users\harri\OneDrive\Documents\DataScienceProjects\NBACareerPredictorML\data\Total_Filtered_NBA_College_Stats.csv")

#Initial Inspection - Shape of the dataset
df.shape

(314, 51)

In [4]:
#Shows the data types for the dataset
df.dtypes

Name          object
Team          object
Conf           int64
Class          int64
Pos            int64
G              int64
MP           float64
FG           float64
FGA          float64
FG%          float64
3P           float64
3PA          float64
3P%          float64
2P           float64
2PA          float64
2P%          float64
eFG%         float64
FT           float64
FTA          float64
FT%          float64
ORB          float64
DRB          float64
TRB          float64
AST          float64
STL          float64
BLK          float64
TOV          float64
PF           float64
PTS          float64
ORTG         float64
DRTG         float64
PER          float64
TS%          float64
3PAr         float64
FTr          float64
ORB%         float64
DRB%         float64
TRB%         float64
AST%         float64
STL%         float64
BLK%         float64
TOV%         float64
USG%         float64
OWS          float64
DWS          float64
WS           float64
WS/40        float64
OBPM         float64
DBPM         float64
BPM          float64
player_id     object
dtype: object

In [5]:
#Shows the first five rows of the dataset
df.head()

,Name,Team,Conf,Class,Pos,G,MP,FG,FGA,FG%,...,TOV%,USG%,OWS,DWS,WS,WS/40,OBPM,DBPM,BPM,player_id
0,Aaron Gordon,Arizona,3,0,1,38,1187.0,5.0,10.1,0.495,...,12.4,23.2,2.1,3.3,5.4,0.183,3.3,3.9,7.2,gordoaa01
1,Aaron Holiday,UCLA,3,2,0,33,1244.0,6.4,13.9,0.461,...,20.6,27.2,3.7,1.2,4.9,0.157,4.9,0.1,5.0,holidaa01
2,Aaron Nesmith,Vanderbilt,3,1,1,14,500.0,7.5,14.6,0.512,...,11.6,23.7,2.2,0.4,2.6,0.207,8.6,0.3,8.9,nesmiaa01
3,Aaron Wiggins,Maryland,3,2,1,30,993.0,5.3,12.0,0.443,...,14.5,24.9,2.1,1.6,3.7,0.145,4.1,1.7,5.8,wiggiaa01
4,Al Horford,Florida,3,2,1,38,1058.0,7.0,11.6,0.608,...,14.5,17.8,3.5,4.0,7.5,0.283,0.0,0.0,0.0,horfoal01

In [6]:
#Shows Non-Null Count and Dtype
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 314 entries, 0 to 313
Data columns (total 51 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       314 non-null    object
 1   Team       314 non-null    object
 2   Conf       314 non-null    int64
 3   Class      314 non-null    int64
 4   Pos        314 non-null    int64
 5   G          314 non-null    int64
 6   MP         314 non-null    float64
 7   FG         314 non-null    float64
 8   FGA        314 non-null    float64
 9   FG%        314 non-null    float64
 10  3P         314 non-null    float64
 11  3PA        314 non-null    float64
 12  3P%        314 non-null    float64
 13  2P         314 non-null    float64
 14  2PA        314 non-null    float64
 15  2P%        314 non-null    float64
 16  eFG%       314 non-null    float64
 17  FT         314 non-null    float64
 18  FTA        314 non-null    float64
 19  FT%        314 non-null    float64
 20  ORB        314 non-null    float64
 21  DRB        314 non-null    float64
 22  TRB        314 non-null    float64
 23  AST        314 non-null    float64
 24  STL        314 non-null    float64
 25  BLK        314 non-null    float64
 26  TOV        314 non-null    float64
 27  PF         314 non-null    float64
 28  PTS        314 non-null    float64
 29  ORTG       314 non-null    float64
 30  DRTG       314 non-null    float64
 31  PER        314 non-null    float64
 32  TS%        314 non-null    float64
 33  3PAr       314 non-null    float64
 34  FTr        314 non-null    float64
 35  ORB%       314 non-null    float64
 36  DRB%       314 non-null    float64
 37  TRB%       314 non-null    float64
 38  AST%       314 non-null    float64
 39  STL%       314 non-null    float64
 40  BLK%       314 non-null    float64
 41  TOV%       314 non-null    float64
 42  USG%       314 non-null    float64
 43  OWS        314 non-null    float64
 44  DWS        314 non-null    float64
 45  WS         314 non-null    float64
 46  WS/40      314 non-null    float64
 47  OBPM       314 non-null    float64
 48  DBPM       314 non-null    float64
 49  BPM        314 non-null    float64
 50  player_id  314 non-null    object
dtypes: float64(44), int64(4), object(3)
memory usage: 125.2+ KB

In [7]:
#Checks to see if there are any null values 
df.isnull().sum()

Name         0
Team         0
Conf         0
Class        0
Pos          0
G            0
MP           0
FG           0
FGA          0
FG%          0
3P           0
3PA          0
3P%          0
2P           0
2PA          0
2P%          0
eFG%         0
FT           0
FTA          0
FT%          0
ORB          0
DRB          0
TRB          0
AST          0
STL          0
BLK          0
TOV          0
PF           0
PTS          0
ORTG         0
DRTG         0
PER          0
TS%          0
3PAr         0
FTr          0
ORB%         0
DRB%         0
TRB%         0
AST%         0
STL%         0
BLK%         0
TOV%         0
USG%         0
OWS          0
DWS          0
WS           0
WS/40        0
OBPM         0
DBPM         0
BPM          0
player_id    0
dtype: int64

In [8]:
#Checks to see if there are any duplicated rows
df.duplicated().sum()

np.int64(0)

In [ ]:
numeric_cols = df.select_dtypes(include='number').columns

#Prints out the amount of outliers in the dataset
for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = df[(df[col] < lower) | (df[col] > upper)]
    print(col, ": ", len(outliers), "outliers")

Conf :  0 outliers
Class :  0 outliers
Pos :  0 outliers
G :  27 outliers
MP :  16 outliers
FG :  12 outliers
FGA :  11 outliers
FG% :  13 outliers
3P :  0 outliers
3PA :  0 outliers
3P% :  35 outliers
2P :  6 outliers
2PA :  2 outliers
2P% :  8 outliers
eFG% :  10 outliers
FT :  11 outliers
FTA :  4 outliers
FT% :  11 outliers
ORB :  3 outliers
DRB :  8 outliers
TRB :  5 outliers
AST :  11 outliers
STL :  5 outliers
BLK :  25 outliers
TOV :  4 outliers
PF :  13 outliers
PTS :  10 outliers
ORTG :  18 outliers
DRTG :  10 outliers
PER :  10 outliers
TS% :  9 outliers
3PAr :  0 outliers
FTr :  6 outliers
ORB% :  11 outliers
DRB% :  12 outliers
TRB% :  8 outliers
AST% :  23 outliers
STL% :  6 outliers
BLK% :  27 outliers
TOV% :  1 outliers
USG% :  25 outliers
OWS :  3 outliers
DWS :  4 outliers
WS :  6 outliers
WS/40 :  15 outliers
OBPM :  7 outliers
DBPM :  6 outliers
BPM :  5 outliers

In [ ]:
#Comparing two columns' means
print(df['PTS'].mean())
print(df['G'].mean())

15.809554140127391
30.662420382165607

In [ ]:
#Comparing two columns' medians
print(df['PTS'].median())
print(df['G'].median())

16.1
33.0

In [13]:
#Gets all central tendency stats at once
df.describe()

,Conf,Class,Pos,G,MP,FG,FGA,FG%,3P,3PA,...,BLK%,TOV%,USG%,OWS,DWS,WS,WS/40,OBPM,DBPM,BPM
count,314.000000,314.000000,314.000000,314.000000,314.000000,314.000000,314.000000,314.000000,314.000000,314.000000,...,314.000000,314.000000,314.000000,314.000000,314.000000,314.000000,314.000000,314.000000,314.000000,314.000000
mean,2.264331,1.108280,0.971338,30.662420,939.591401,5.577707,11.549045,0.488838,1.338217,3.695860,...,5.013280,15.863376,27.440424,2.641943,1.837768,4.474618,0.181803,4.527379,2.561045,7.114857
std,1.106271,1.167065,0.734242,7.708801,287.861590,1.506964,3.189382,0.076852,0.945042,2.398458,...,9.259608,3.439894,19.494358,1.592090,0.775000,2.044829,0.077278,2.762170,1.893561,3.539181
min,0.000000,0.000000,0.000000,3.000000,17.800000,0.400000,1.700000,0.182000,0.000000,0.000000,...,0.000000,7.100000,15.800000,-1.100000,0.045000,-0.700000,-0.429000,-8.300000,-1.000000,-7.400000
25%,1.000000,0.000000,0.000000,29.000000,814.000000,4.700000,9.600000,0.439000,0.600000,1.825000,...,1.200000,13.525000,21.700000,1.725000,1.392500,3.300000,0.153250,2.850000,1.300000,5.000000
50%,3.000000,1.000000,1.000000,33.000000,1004.000000,5.600000,11.600000,0.476000,1.300000,3.600000,...,2.300000,15.600000,24.900000,2.800000,1.900000,4.600000,0.187000,4.600000,2.300000,7.100000
75%,3.000000,2.000000,2.000000,36.000000,1134.500000,6.400000,13.300000,0.522000,2.100000,5.375000,...,5.300000,18.175000,27.867500,3.600000,2.300000,5.800000,0.217750,6.000000,3.500000,9.275000
max,3.000000,3.000000,2.000000,40.000000,1374.000000,10.300000,21.300000,0.769000,4.300000,10.600000,...,98.788000,26.800000,292.509000,6.700000,5.700000,11.300000,0.434000,12.800000,19.307000,19.105000

In [19]:
#Creates folder for histogram plots
os.makedirs("reports/histogram_folder", exist_ok=True)
#Create histograms with mean and median lines
for col in numeric_cols:
    plt.figure(figsize=(8,4))
    plt.hist(df[col].dropna(), bins=40)
    plt.axvline(df[col].mean(), color='red', label='Mean')
    plt.axvline(df[col].median(), color='green', label='Median')
    plt.legend()
    plt.title(f"{col} Distribution")
    try:
        plt.savefig(f"reports/histogram_folder/{col}_mean_median_histogram.png", dpi=300)
    except FileNotFoundError as e:
        plt.savefig(f"reports/histogram_folder/WS40_mean_median_histogram.png", dpi=300)
    plt.close()

In [ ]:
#Computes the Std, Var, Range, Skewness, and Kurtosis
for col in numeric_cols:
    print(f"{col}:")
    print(f"    std:    {df[col].std()}")
    print(f"    var:    {df[col].var()}")
    print(f"    range:    {df[col].max() - df[col].min()}")
    print(f"    skewness:   {df[col].skew()}")
    print(f"    kurtosis:    {df[col].kurt()}")
    print()

Conf:
    std:    1.1062709856916593
    var:    1.2238354937831952
    range:    3
    skewness:   -0.9940491368407945
    kurtosis:    -0.703612832356892

Class:
    std:    1.1670646274003031
    var:    1.3620398445290085
    range:    3
    skewness:   0.5524496919024997
    kurtosis:    -1.207331082030643

Pos:
    std:    0.7342424280739295
    var:    0.5391119431838995
    range:    2
    skewness:   0.0448146445242152
    kurtosis:    -1.1375112241087384

G:
    std:    7.708800945309687
    var:    59.42561201440752
    range:    37
    skewness:   -1.8201092467732711
    kurtosis:    3.2855524607561515

MP:
    std:    287.86158973707046
    var:    82864.29484595348
    range:    1356.2
    skewness:   -1.251085272583098
    kurtosis:    1.3525862260559345

FG:
    std:    1.5069635477767043
    var:    2.270939134327751
    range:    9.9
    skewness:   0.20591988026428054
    kurtosis:    0.7134688821290416

FGA:
    std:    3.1893817008612317
    var:    10.172155633788485
    range:    19.6
    skewness:   0.3021075122026126
    kurtosis:    0.5852895489368599

FG%:
    std:    0.07685247301694019
    var:    0.0059063026088195195
    range:    0.587
    skewness:   0.6127206279532508
    kurtosis:    1.579629177435585

3P:
    std:    0.9450415432386653
    var:    0.893103518446918
    range:    4.3
    skewness:   0.4178475846794926
    kurtosis:    -0.4163783397457679

3PA:
    std:    2.398458382563567
    var:    5.752602612889441
    range:    10.6
    skewness:   0.25997434023027677
    kurtosis:    -0.5075552927048554

3P%:
    std:    0.13050535170026165
    var:    0.017031646822408986
    range:    1.0
    skewness:   -0.902404314338082
    kurtosis:    3.356282671960999

2P:
    std:    1.5307479185970392
    var:    2.3431891902891677
    range:    9.399999999999999
    skewness:   0.5399551079246293
    kurtosis:    0.355521099386058

2PA:
    std:    2.5157520473385615
    var:    6.329008363688163
    range:    14.299999999999999
    skewness:   0.2560790830979309
    kurtosis:    0.03622530136151969

2P%:
    std:    0.0751401951729445
    var:    0.005646048930628192
    range:    0.6000000000000001
    skewness:   0.20665065511100217
    kurtosis:    1.4492521266855505

eFG%:
    std:    0.06592477466177689
    var:    0.004346075914206059
    range:    0.543
    skewness:   -0.16408474821809618
    kurtosis:    2.3199317688334338

FT:
    std:    1.379023312711755
    var:    1.901705297002503
    range:    7.9
    skewness:   0.7574668356229122
    kurtosis:    0.666420033804787

FTA:
    std:    1.7229311915111165
    var:    2.9684918906819155
    range:    10.9
    skewness:   0.6361486848541478
    kurtosis:    0.39264499320891577

FT%:
    std:    0.1045424444804635
    var:    0.010929122697950794
    range:    1.0
    skewness:   -1.825104137888799
    kurtosis:    9.013774085713223

ORB:
    std:    1.0439381601593214
    var:    1.0898068822368288
    range:    5.8
    skewness:   0.7699639528141218
    kurtosis:    0.22057740925627023

DRB:
    std:    1.7939105089793106
    var:    3.218114914226409
    range:    11.6
    skewness:   0.8693784315305648
    kurtosis:    1.094157284507629

TRB:
    std:    2.537077526928965
    var:    6.436762377647993
    range:    14.1
    skewness:   0.6739408325174241
    kurtosis:    0.17597931928346977

AST:
    std:    1.813905916888203
    var:    3.2902546753220325
    range:    10.3
    skewness:   1.3526385196484454
    kurtosis:    2.2474719199070305

STL:
    std:    0.5794799326363238
    var:    0.33579699232819843
    range:    3.9
    skewness:   1.011560011795034
    kurtosis:    1.8736554171121504

BLK:
    std:    0.903951471909914
    var:    0.8171282635681
    range:    5.3
    skewness:   1.7679538301094717
    kurtosis:    3.4302686389523096

TOV:
    std:    0.8481578307764956
    var:    0.7193717059074907
    range:    6.9
    skewness:   1.147333559711493
    kurtosis:    3.9296376301035902

PF:
    std:    0.983284938594412
    var:    0.9668492704666165
    range:    6.8
    skewness:   1.1823641140328218
    kurtosis:    2.413012011657929

PTS:
    std:    4.346410269255409
    var:    18.891282228688876
    range:    29.9
    skewness:   0.25522576251705864
    kurtosis:    0.8791071194777849

ORTG:
    std:    18.25497580239984
    var:    333.24414154620376
    range:    140.6
    skewness:   -3.794026349609058
    kurtosis:    19.916867225095373

DRTG:
    std:    13.691614389280991
    var:    187.4603045847663
    range:    122.0
    skewness:   -5.333319991090363
    kurtosis:    35.1923288002046

PER:
    std:    6.273898078941267
    var:    39.36179710494292
    range:    52.7
    skewness:   0.20502391792131347
    kurtosis:    1.867330509486206

TS%:
    std:    0.058843303963653726
    var:    0.0034625344213589466
    range:    0.497
    skewness:   -0.6139601968302136
    kurtosis:    4.1526967625797

3PAr:
    std:    0.1764967982659513
    var:    0.031151119798131906
    range:    0.764
    skewness:   -0.16541380858652074
    kurtosis:    -0.740603295406209

FTr:
    std:    0.14331330561844552
    var:    0.02053870356728597
    range:    1.038
    skewness:   0.8684456240381971
    kurtosis:    1.2670330053441194

ORB%:
    std:    6.011923957677811
    var:    36.14322967290043
    range:    56.01
    skewness:   2.955746048466794
    kurtosis:    16.56380910517388

DRB%:
    std:    15.366394045774527
    var:    236.12606597001485
    range:    260.092
    skewness:   12.641707335355354
    kurtosis:    197.6338579506016

TRB%:
    std:    10.031315579258617
    var:    100.62729225067663
    range:    156.055
    skewness:   9.599313470439085
    kurtosis:    132.06819202166102

AST%:
    std:    26.474910416920633
    var:    700.9208815839727
    range:    229.064
    skewness:   4.589687002571519
    kurtosis:    26.25434455652784

STL%:
    std:    1.2099536826234867
    var:    1.4639879140941372
    range:    12.21
    skewness:   2.540287028322888
    kurtosis:    15.757314426862406

BLK%:
    std:    9.259607663791188
    var:    85.7403340873405
    range:    98.788
    skewness:   5.940855101662847
    kurtosis:    45.99886867793376

TOV%:
    std:    3.439894131319141
    var:    11.832871634683869
    range:    19.700000000000003
    skewness:   0.12286642506585486
    kurtosis:    -0.060701676142872696

USG%:
    std:    19.49435830869899
    var:    380.0300058679413
    range:    276.709
    skewness:   10.162872957898106
    kurtosis:    122.91310036234984

OWS:
    std:    1.5920901576813393
    var:    2.534751070185792
    range:    7.800000000000001
    skewness:   -0.067328549265756
    kurtosis:    -0.27814052208636575

DWS:
    std:    0.7750001835074758
    var:    0.6006252844366212
    range:    5.655
    skewness:   0.4939090327011716
    kurtosis:    1.7520456786282343

WS:
    std:    2.0448287445888695
    var:    4.181324594696892
    range:    12.0
    skewness:   -0.14084509869151973
    kurtosis:    0.16102222331536753

WS/40:
    std:    0.0772778018038498
    var:    0.0059718586516350905
    range:    0.863
    skewness:   -2.769869276929736
    kurtosis:    20.48385307698571

OBPM:
    std:    2.762169624557542
    var:    7.629581034828352
    range:    21.1
    skewness:   -0.1474572087047749
    kurtosis:    1.1852738451008555

DBPM:
    std:    1.8935610613902596
    var:    3.5855734932134067
    range:    20.307
    skewness:   2.5713537556008537
    kurtosis:    18.847603621516427

BPM:
    std:    3.5391809663117497
    var:    12.525801912303372
    range:    26.505000000000003
    skewness:   0.040235797444358984
    kurtosis:    1.1335464814789171