In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

%matplotlib inline
sns.set_theme(style="whitegrid")

In [8]:
#Reads the .csv file
df = pd.read_csv(r"C:\Users\harri\OneDrive\Documents\DataScienceProjects\NBACareerPredictorML\data\NBAProspects2026.csv")

#Initial Inspection - Shape of the dataset
df.shape

(62, 52)

In [4]:
#Show the data types for the dataset
df.dtypes

Name      object
Team      object
Conf      object
Class     object
Pos       object
G          int64
GS         int64
MP       float64
FG       float64
FGA      float64
FG%      float64
3P       float64
3PA      float64
3P%      float64
2P       float64
2PA      float64
2P%      float64
eFG%     float64
FT       float64
FTA      float64
FT%      float64
ORB      float64
DRB      float64
TRB      float64
AST      float64
STL      float64
BLK      float64
TOV      float64
PF       float64
PTS      float64
ORTG     float64
DRTG     float64
PER      float64
TS%      float64
3PAr     float64
FTr      float64
PProd      int64
ORB%     float64
DRB%     float64
TRB%     float64
AST%     float64
STL%     float64
BLK%     float64
TOV%     float64
USG%     float64
OWS      float64
DWS      float64
WS       float64
WS/40    float64
OBPM     float64
DBPM     float64
BPM      float64
dtype: object

In [5]:
#Shows the first five rows of the dataset
df.head()

,Name,Team,Conf,Class,Pos,G,GS,MP,FG,FGA,...,BLK%,TOV%,USG%,OWS,DWS,WS,WS/40,OBPM,DBPM,BPM
0,AJ Dybantsa,BYU,Big 12,FR,F,35,35,1217.0,10.1,19.9,...,1.1,12.7,33.9,4.8,1.6,6.4,0.209,9.5,2.2,11.7
1,Darryn Peterson,Kansas,Big 12,FR,G,24,23,697.0,9.0,20.4,...,2.3,8.3,33.5,2.0,1.4,3.5,0.198,9.3,4.8,14.1
2,Cameron Boozer,Duke,ACC,FR,F,38,38,1271.0,9.1,16.4,...,2.2,12.8,29.9,6.9,3.5,10.4,0.327,12.7,6.0,18.7
3,Caleb Wilson,UNC,ACC,FR,F,24,24,751.0,9.1,15.7,...,4.4,11.0,28.7,3.0,1.7,4.8,0.254,8.7,5.3,14.0
4,Keaton Wagler,Illinois,Big Ten,FR,G,37,37,1255.0,6.4,14.5,...,1.3,10.6,25.2,5.5,1.8,7.2,0.230,8.8,3.5,12.3

In [10]:
#Shows the Non-Null Count and Dtype
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62 entries, 0 to 61
Data columns (total 52 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    62 non-null     object
 1   Team    62 non-null     object
 2   Conf    62 non-null     object
 3   Class   62 non-null     object
 4   Pos     62 non-null     object
 5   G       62 non-null     int64
 6   GS      62 non-null     int64
 7   MP      62 non-null     float64
 8   FG      62 non-null     float64
 9   FGA     62 non-null     float64
 10  FG%     62 non-null     float64
 11  3P      62 non-null     float64
 12  3PA     62 non-null     float64
 13  3P%     62 non-null     float64
 14  2P      62 non-null     float64
 15  2PA     62 non-null     float64
 16  2P%     62 non-null     float64
 17  eFG%    62 non-null     float64
 18  FT      62 non-null     float64
 19  FTA     62 non-null     float64
 20  FT%     62 non-null     float64
 21  ORB     62 non-null     float64
 22  DRB     62 non-null     float64
 23  TRB     62 non-null     float64
 24  AST     62 non-null     float64
 25  STL     62 non-null     float64
 26  BLK     62 non-null     float64
 27  TOV     62 non-null     float64
 28  PF      62 non-null     float64
 29  PTS     62 non-null     float64
 30  ORTG    62 non-null     float64
 31  DRTG    62 non-null     float64
 32  PER     62 non-null     float64
 33  TS%     62 non-null     float64
 34  3PAr    62 non-null     float64
 35  FTr     62 non-null     float64
 36  PProd   62 non-null     int64
 37  ORB%    62 non-null     float64
 38  DRB%    62 non-null     float64
 39  TRB%    62 non-null     float64
 40  AST%    62 non-null     float64
 41  STL%    62 non-null     float64
 42  BLK%    62 non-null     float64
 43  TOV%    62 non-null     float64
 44  USG%    62 non-null     float64
 45  OWS     62 non-null     float64
 46  DWS     62 non-null     float64
 47  WS      62 non-null     float64
 48  WS/40   62 non-null     float64
 49  OBPM    62 non-null     float64
 50  DBPM    62 non-null     float64
 51  BPM     62 non-null     float64
dtypes: float64(44), int64(3), object(5)
memory usage: 25.3+ KB

In [9]:
#Checks to see if there are any null values
df.isnull().sum()

Name     0
Team     0
Conf     0
Class    0
Pos      0
G        0
GS       0
MP       0
FG       0
FGA      0
FG%      0
3P       0
3PA      0
3P%      0
2P       0
2PA      0
2P%      0
eFG%     0
FT       0
FTA      0
FT%      0
ORB      0
DRB      0
TRB      0
AST      0
STL      0
BLK      0
TOV      0
PF       0
PTS      0
ORTG     0
DRTG     0
PER      0
TS%      0
3PAr     0
FTr      0
PProd    0
ORB%     0
DRB%     0
TRB%     0
AST%     0
STL%     0
BLK%     0
TOV%     0
USG%     0
OWS      0
DWS      0
WS       0
WS/40    0
OBPM     0
DBPM     0
BPM      0
dtype: int64

In [11]:
#Checks to see if there are any duplicated rows
df.duplicated().sum()

np.int64(0)

In [12]:
numeric_cols = df.select_dtypes(include='number').columns

#Prints out the amount of outliers in the dataset
for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = df[(df[col] < lower) | (df[col] > upper)]
    print(col, ": ", len(outliers), "outliers")

G :  4 outliers
GS :  6 outliers
MP :  4 outliers
FG :  1 outliers
FGA :  2 outliers
FG% :  0 outliers
3P :  0 outliers
3PA :  0 outliers
3P% :  7 outliers
2P :  0 outliers
2PA :  0 outliers
2P% :  1 outliers
eFG% :  0 outliers
FT :  0 outliers
FTA :  0 outliers
FT% :  3 outliers
ORB :  0 outliers
DRB :  0 outliers
TRB :  0 outliers
AST :  1 outliers
STL :  2 outliers
BLK :  2 outliers
TOV :  0 outliers
PF :  1 outliers
PTS :  0 outliers
ORTG :  2 outliers
DRTG :  0 outliers
PER :  0 outliers
TS% :  0 outliers
3PAr :  0 outliers
FTr :  1 outliers
PProd :  2 outliers
ORB% :  0 outliers
DRB% :  0 outliers
TRB% :  0 outliers
AST% :  1 outliers
STL% :  2 outliers
BLK% :  2 outliers
TOV% :  3 outliers
USG% :  0 outliers
OWS :  1 outliers
DWS :  1 outliers
WS :  3 outliers
WS/40 :  2 outliers
OBPM :  0 outliers
DBPM :  1 outliers
BPM :  1 outliers

In [13]:
#Comparing two columns' means
print(df['PER'].mean())
print(df['3P%'].mean())

22.469354838709673
0.3306935483870967

In [14]:
#Comparing two columns' medians
print(df['PER'].median())
print(df['3P%'].median())

22.55
0.354

In [15]:
#Gets all central tendency stats at once
df.describe()

,G,GS,MP,FG,FGA,FG%,3P,3PA,3P%,2P,...,BLK%,TOV%,USG%,OWS,DWS,WS,WS/40,OBPM,DBPM,BPM
count,62.000000,62.000000,62.000000,62.000000,62.000000,62.000000,62.000000,62.000000,62.000000,62.000000,...,62.000000,62.000000,62.000000,62.000000,62.000000,62.000000,62.000000,62.000000,62.000000,62.000000
mean,33.387097,30.064516,984.259677,7.008387,14.129677,0.502500,1.779839,4.908871,0.330694,5.234355,...,2.959677,12.087097,23.927419,3.208065,1.891935,5.100000,0.195194,5.891935,3.741935,9.637097
std,6.491747,10.582805,282.288227,1.344070,2.890592,0.069906,1.176528,3.043126,0.101650,1.697007,...,2.953379,3.945759,4.636002,1.341922,0.803741,1.761333,0.042066,2.643600,1.825911,3.265228
min,4.000000,0.000000,31.100000,3.700000,6.900000,0.380000,0.000000,0.000000,0.000000,1.400000,...,0.000000,6.200000,12.700000,0.000000,0.100000,0.100000,0.051000,-0.800000,0.600000,1.900000
25%,31.000000,28.250000,905.250000,6.225000,12.575000,0.446500,0.750000,2.200000,0.327250,4.150000,...,0.925000,9.325000,20.925000,2.150000,1.400000,4.100000,0.173000,4.100000,2.300000,7.500000
50%,35.000000,34.000000,1040.000000,7.050000,14.050000,0.490000,1.650000,4.800000,0.354000,5.050000,...,2.250000,11.650000,23.950000,3.100000,1.800000,5.050000,0.194000,6.250000,3.550000,9.600000
75%,37.000000,37.000000,1178.000000,7.800000,15.700000,0.558250,2.675000,6.825000,0.390000,6.275000,...,4.150000,13.600000,26.850000,4.000000,2.400000,5.875000,0.224250,7.700000,4.800000,11.675000
max,40.000000,40.000000,1396.000000,10.100000,20.400000,0.683000,4.300000,12.400000,0.464000,8.800000,...,17.400000,23.300000,33.900000,6.900000,5.400000,11.800000,0.327000,12.700000,8.900000,18.700000

In [16]:
#Creates folder for histogram plots
os.makedirs("reports/prospect_histogram_folder", exist_ok=True)
#Create histograms with mean and median lines
for col in numeric_cols:
    plt.figure(figsize=(8,4))
    plt.hist(df[col].dropna(), bins=40)
    plt.axvline(df[col].mean(), color='red', label='Mean')
    plt.axvline(df[col].median(), color='green', label='Median')
    plt.legend()
    plt.title(f"{col} Distribution")
    try:
        plt.savefig(f"reports/prospect_histogram_folder/{col}_mean_median_histogram.png", dpi=300)
    except FileNotFoundError as e:
        plt.savefig(f"reports/prospect_histogram_folder/WS40_mean_median_histogram.png", dpi=300)
    plt.close()

In [17]:
#Computes the Std, Var, Range, Skewness, and Kurtosis
for col in numeric_cols:
    print(f"{col}:")
    print(f"    std:    {df[col].std()}")
    print(f"    var:    {df[col].var()}")
    print(f"    range:    {df[col].max() - df[col].min()}")
    print(f"    skewness:   {df[col].skew()}")
    print(f"    kurtosis:    {df[col].kurt()}")
    print()

G:
    std:    6.4917471913991385
    var:    42.142781597038606
    range:    36
    skewness:   -2.2506995131440166
    kurtosis:    6.622369613401933

GS:
    std:    10.582805366922413
    var:    111.99576943416183
    range:    40
    skewness:   -1.7128458269825197
    kurtosis:    2.1715023042414328

MP:
    std:    282.2882269977506
    var:    79686.64310153358
    range:    1364.9
    skewness:   -1.4813899113021411
    kurtosis:    2.7243911744702847

FG:
    std:    1.3440703942683991
    var:    1.80652522474881
    range:    6.3999999999999995
    skewness:   -3.902314458858998e-05
    kurtosis:    -0.18432433114457325

FGA:
    std:    2.8905924106313896
    var:    8.355524484399787
    range:    13.499999999999998
    skewness:   -0.15464365767294397
    kurtosis:    0.09686847925029474

FG%:
    std:    0.06990643629928202
    var:    0.0048869098360655745
    range:    0.30300000000000005
    skewness:   0.5088926839577083
    kurtosis:    -0.3024342327055334

3P:
    std:    1.1765279454164481
    var:    1.3842180063458487
    range:    4.3
    skewness:   0.18279905022832488
    kurtosis:    -0.9219522042812818

3PA:
    std:    3.043126145458991
    var:    9.260616737176097
    range:    12.4
    skewness:   0.2595590392636411
    kurtosis:    -0.5873880717386561

3P%:
    std:    0.10164976654996093
    var:    0.010332675039661557
    range:    0.464
    skewness:   -2.1003377374260275
    kurtosis:    4.319341497075527

2P:
    std:    1.697006642343079
    var:    2.8798315441565308
    range:    7.4
    skewness:   0.20725177038872789
    kurtosis:    -0.29310424993537243

2PA:
    std:    2.7398644573854374
    var:    7.506857244843998
    range:    12.2
    skewness:   0.07792407259481271
    kurtosis:    -0.31369424752644326

2P%:
    std:    0.06878480033605743
    var:    0.004731348757271285
    range:    0.34
    skewness:   0.295508693647243
    kurtosis:    0.11221494925530351

eFG%:
    std:    0.048070119438859395
    var:    0.002310736382866208
    range:    0.23100000000000004
    skewness:   0.3712713168616426
    kurtosis:    0.010887165763398876

FT:
    std:    1.7328575361562277
    var:    3.002795240613432
    range:    6.6
    skewness:   -0.05868511228941065
    kurtosis:    -0.6753292374670741

FTA:
    std:    2.17765638582939
    var:    4.742187334743522
    range:    8.399999999999999
    skewness:   -0.19630924727219715
    kurtosis:    -0.6248240480029597

FT%:
    std:    0.10861161210711105
    var:    0.011796482284505553
    range:    0.583
    skewness:   -1.6758634890136024
    kurtosis:    3.888710487303643

ORB:
    std:    1.5934316277125309
    var:    2.5390243521946054
    range:    6.7
    skewness:   0.6127062862397666
    kurtosis:    -0.29745269893640947

DRB:
    std:    2.001735074983143
    var:    4.0069433104177685
    range:    8.1
    skewness:   0.38765355781242455
    kurtosis:    -0.6022270844848259

TRB:
    std:    3.378542565633119
    var:    11.414549867794818
    range:    14.599999999999998
    skewness:   0.43490347274401575
    kurtosis:    -0.5222773671496324

AST:
    std:    1.9032911460608746
    var:    3.622517186673717
    range:    9.600000000000001
    skewness:   1.0309871115500058
    kurtosis:    1.3371285992035493

STL:
    std:    0.6075641650897592
    var:    0.3691342147012162
    range:    2.9
    skewness:   1.144758627375899
    kurtosis:    1.9740073389888972

BLK:
    std:    1.06923623630714
    var:    1.1432661290322579
    range:    6.3
    skewness:   2.58610549877436
    kurtosis:    9.553555706164616

TOV:
    std:    0.7552493713358693
    var:    0.5704016129032259
    range:    3.3000000000000003
    skewness:   0.3321586226605533
    kurtosis:    -0.6403050812012645

PF:
    std:    1.0859046556699679
    var:    1.1791889212057114
    range:    5.199999999999999
    skewness:   1.102168402513586
    kurtosis:    1.1613555455634264

PTS:
    std:    4.355539517028836
    var:    18.970724484399785
    range:    19.599999999999998
    skewness:   -0.25207144316288943
    kurtosis:    -0.01020846300089051

ORTG:
    std:    8.842484940669399
    var:    78.18953992596511
    range:    56.2
    skewness:   -0.34655953156863245
    kurtosis:    2.2877482977867314

DRTG:
    std:    7.034376006148319
    var:    49.48244579587518
    range:    29.700000000000003
    skewness:   0.008928548678274442
    kurtosis:    -0.7390443711487453

PER:
    std:    4.379182823300968
    var:    19.177242199894234
    range:    20.500000000000004
    skewness:   0.042386916736945335
    kurtosis:    -0.15452090011529185

TS%:
    std:    0.04198918611257683
    var:    0.001763091750396615
    range:    0.20099999999999996
    skewness:   -0.16593521979109557
    kurtosis:    -0.09506971021839306

3PAr:
    std:    0.1915679410664032
    var:    0.036698276044420934
    range:    0.751
    skewness:   0.09887268638960076
    kurtosis:    -0.7396556647471204

FTr:
    std:    0.15144665694403445
    var:    0.022936089899524056
    range:    0.8250000000000001
    skewness:   0.5658982094858764
    kurtosis:    1.3215765316672097

PProd:
    std:    212.69571694405568
    var:    45239.46800634586
    range:    1592
    skewness:   2.0746305749785234
    kurtosis:    10.635957133093736

ORB%:
    std:    4.97898731152573
    var:    24.790314648334217
    range:    20.8
    skewness:   0.733865066877211
    kurtosis:    0.02155628517318231

DRB%:
    std:    5.4977330552414845
    var:    30.225068746694866
    range:    20.5
    skewness:   0.3598179203593698
    kurtosis:    -0.9057658854449575

TRB%:
    std:    4.777703868701666
    var:    22.82645425700687
    range:    18.9
    skewness:   0.2927969960141078
    kurtosis:    -0.934039158941768

AST%:
    std:    8.610502345077487
    var:    74.14075063458489
    range:    39.9
    skewness:   0.7100237066112259
    kurtosis:    0.2553407254994302

STL%:
    std:    0.900232063623886
    var:    0.8104177683765204
    range:    4.7
    skewness:   1.144841944005085
    kurtosis:    2.2303283342556273

BLK%:
    std:    2.953378708509154
    var:    8.722445795875197
    range:    17.4
    skewness:   2.5669986791894606
    kurtosis:    9.366618399805565

TOV%:
    std:    3.9457586222721894
    var:    15.569011105235328
    range:    17.1
    skewness:   1.0795549086164575
    kurtosis:    1.112376649423617

USG%:
    std:    4.636001999845349
    var:    21.492514542570074
    range:    21.2
    skewness:   -0.15563690006473402
    kurtosis:    -0.0027584968102951635

OWS:
    std:    1.3419215958989281
    var:    1.800753569539926
    range:    6.9
    skewness:   0.32861904435633366
    kurtosis:    0.2610471242396506

DWS:
    std:    0.8037409229218518
    var:    0.6459994711792703
    range:    5.300000000000001
    skewness:   1.229160898056292
    kurtosis:    4.811091514965884

WS:
    std:    1.7613333250600847
    var:    3.1022950819672137
    range:    11.700000000000001
    skewness:   0.8583821360902054
    kurtosis:    3.9806107864528397

WS/40:
    std:    0.04206623922202347
    var:    0.0017695684822845057
    range:    0.276
    skewness:   -0.14355058312283167
    kurtosis:    2.1221600759042336

OBPM:
    std:    2.643600276516657
    var:    6.988622421998944
    range:    13.5
    skewness:   -0.30945934023648985
    kurtosis:    0.18765449968712344

DBPM:
    std:    1.8259108113079898
    var:    3.3339502908514014
    range:    8.3
    skewness:   0.6872634431860394
    kurtosis:    0.3085201662572352

BPM:
    std:    3.2652283263606714
    var:    10.661716023268111
    range:    16.8
    skewness:   -0.05576965816466413
    kurtosis:    0.6142688916387224